export const AUTH_LOADING_STARTS = "AUTH_LOADING_STARTS";
export const AUTH_LOADING_ENDS = "AUTH_LOADING_ENDS";
export const REDIRECT_TO = "REDIRECT_TO";
export const GET_LOGGED_IN_USER_DETAILS = "GET_LOGGED_IN_USER_DETAILS";
export const GET_SUCCESS_RESPONSE = "GET_SUCCESS_RESPONSE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_AUTH_ERROR = "GET_AUTH_ERROR";
export const GET_LOGIN_ERROR = "GET_LOGIN_ERROR";
